// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoIntegrador.Database;

namespace ProvaAncelmo.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProvaAncelmo.Models.ClienteViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("bairro")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("cep")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("numero")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("sexo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("ClienteViewModels");
                });

            modelBuilder.Entity("ProvaAncelmo.Models.ProdutoViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("categoria")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("codigoProduto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("observacao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("preco")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("ProdutoViewModels");
                });
#pragma warning restore 612, 618
        }
    }
}
